### ISSUE TITLE
handleInputChange appears to change suggestion filtering when calling setState

### ISSUE THREAD

**Issue by siliconeidolon** [prakhar1989/react-tags#349]
Code to demonstrate the issue:
[Stackblitz code](https://stackblitz.com/edit/react-tag-input-vgxh7c) 

I'm attempting to write a character counter that takes the input value length from the event provided to `handleInputChange`. When I use `setState` to change the value, and if I have a `minQueryLength` prop on the component, the suggestions filter appears to break, showing every suggestion. 

If the `minQueryLength` prop is not set, then the suggestion filter behaves normally.
Likewise, if `handleInputChange` does not use `setState`, the filter behaves normally. 

I'm not sure how these functions relate. If there's another way to accessing the length value of the input, then I'll use that.

Let me know if more detail is required.

**Comment by jpggvilaca** [comment]
+1

**Comment by mikengu** [comment]
It seems to be an Event Loop problem. This is not pretty but if you do this it should fix the event problem. 

```
  handleInputChange(e) {
    window.setTimeout(
      () => {
        this.setState({length: e.length})
      }, 0)
  }
```
The time can be anything. Hopefully, someone will have a more elegant solution.

**Comment by ad1992** [comment]
@siliconeidolon thanks for reporting the bug. Would you like to give a PR for the fix ?

**Comment by siliconeidolon** [comment]
@ad1992 The fix above will work for the implementation of my `handleInputchange` function, but it doesn't solve the underlying issue within the component. If I get time I'll have a look at  submitting a PR for what seems to be causing the problem (https://github.com/prakhar1989/react-tags/blob/master/lib/ReactTags.js#L152)

**Comment by findela** [comment]
There is a problem in suggestion list rendering, I am using **handleInputChange** method to fetch autcomplete data from API and setState suggestions array according to documented format like 
`suggestions: [{ id: "", text: "" }]` 

I have no idea, what's wrong in showing. While console post setState I am able to see the prepared array of objects but it's not displaying. My code is like this -

`EditorService.tagAutocomplete(e).then(function (response) {
                _this.setState({suggestions: []},() => {
                    if(response.flag) {
                        if(response.data.data.length) {
                            console.log(response.data.data.length);
                            response.data.data.map(function (key,i) {
                                _this.state.suggestions.push({id : key.ID, text: key.NAME});
                            });
                            _this.setState(_this.state.suggestions);
                            console.log(_this.state.suggestions);
                        }
                    }
                    else {
                        toast.error(response.data.message ? response.data.message : 'Something went wrong. Try again');
                    }
                });
            });`

Hope this helps to resole my issue.
