### ISSUE TITLE
Drag n Drop error with React 16.5.2

### ISSUE THREAD

**Issue by sendittokeith** [prakhar1989/react-tags#410]
Upon drag, you get error:
invariant.js:42 Uncaught Error: Unable to find node on an unmounted component.

This can be replicated here by updating sample to the version of React listed above:
https://stackblitz.com/edit/react-tag-input-1nelrc?file=index.js

**Comment by hashamkm** [comment]
> Upon drag, you get error:
> invariant.js:42 Uncaught Error: Unable to find node on an unmounted component.
> 
> This can be replicated here by updating sample to the version of React listed above:
> https://stackblitz.com/edit/react-tag-input-1nelrc?file=index.js

I am also facing same issue

**Comment by ad1992** [comment]
@hashamkm @sendittokeith this issue has been fixed.

**Comment by SergeyShablenko** [comment]
Not fixed, I`m facing this issue

React: 16.8.6
React-tag-input: 6.4.0
react-dnd: 7.4.3,
react-dnd-html5-backend: 7.4.0,
